const gaData = [
  [
    '',
    'EU',
    'AU',
    'UK',
    'NZ',
    'CA',
    'US',
    'SG',
    'JP',
    'ID',
    'HK',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    '',
    'EUR',
    'AUD',
    'GBP',
    'NZD',
    'CAD',
    'USD',
    'SGD',
    'JPY',
    'IDR',
    'HKD',
    'CNY',
    'EUR',
    'USD',
    'AUD',
    'CAD',
    'CHF',
    'GBP',
    'JPY',
    'NZD',
    'SGD',
  ],
  [
    'GA Cards Title 1',
    'IBAN',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
  ],
  [
    'GA Cards Value 1',
    '90 • • • • • • • •',
    'Australia',
    'United Kingdom',
    'New Zealand',
    'Canada',
    ' • • • • • • • • • •',
    ' • • • • • • • • • •',
    ' • • • • • • • • • • •',
    '87 • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
    '87 • • • • • • • • • •',
  ],
  [
    'GA Cards Title 2',
    'Account Location',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'ACH routing number',
    'Bank Code',
    'Bank Code',
    'Account Type',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
  ],
  [
    'GA Cards Value 2',
    'Germany (Europe)',
    ' • • • • • • • • •',
    ' • • • • • • • •',
    ' • • - • • • • - • • • • • • • - • •',
    ' • • • • • • • • •',
    '02 • • • • • • •',
    7153,
    '0005',
    'Checking',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
  ],
  [
    'GA Cards Title 3',
    'Bank name',
    'BSB Code',
    'Sort Code',
    'Bank Code',
    'Transit Number',
    'Account Type',
    'Branch Code',
    'Branch Code',
    'Account Location',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
  ],
  [
    'GA Cards Value 3',
    'Banking Circle S.A.',
    13943,
    '0 • • • • •',
    '04',
    10009,
    'Checking',
    '001',
    809,
    'Indonesia',
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
  ],
  [
    'GA Cards Title 4',
    '',
    '',
    '',
    'Branch Code',
    'Financial Institution Number',
    'SWIFT Code',
    'SWIFT Code',
    'Account Type',
    '',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
  ],
  [
    'GA Cards Value 4',
    '',
    '',
    '',
    2024,
    352,
    'C • • • • • • •',
    'CHA • • • • • •',
    'Ordinary',
    '',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
    'SCB • • • • •',
  ],
  [
    'GA Why Title 1',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'n/a',
    'Account Name',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA Why Value 1',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'n/a',
    'Makers Supply Limited',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA Why Title 2',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'n/a',
    'Account Location',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA Why Value 2',
    'Germany (Europe)',
    'Australia',
    'United Kingdom',
    'New Zealand',
    'Canada',
    'United States',
    'Singapore',
    'Japan',
    'n/a',
    'Hong Kong SAR',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA Why Title 3',
    'IBAN',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'n/a',
    'Account no. ',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA Why Value 3',
    '90 • • • • • • • •',
    ' • • • • • • • • •',
    ' • • • • • • • •',
    ' • • - • • • • - • • • • • • • - • •',
    ' • • • • • • • • •',
    ' • • • • • • • • • •',
    ' • • • • • • • • • •',
    ' • • • • • • • • • • •',
    'n/a',
    '87 • • • • • • • • • •',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA Why Title 4',
    'Capabilities',
    'BSB Code',
    'Sort Code',
    'Bank Code',
    'Transit Number',
    'ACH routing number',
    'Bank Code',
    'Bank Code',
    'n/a',
    'Bank Code',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA Why Value 4',
    'Domestic SEPA Transfer',
    '01 • • • •',
    '0 • • • • •',
    '04',
    '10 • • •',
    '02 • • • • • • •',
    7153,
    '0005',
    'n/a',
    '003',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA 2 Fields Title 1',
    'IBAN',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'n/a',
    'Account no. ',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA 2 Fields Value 2',
    '90 • • • • • • • •',
    ' • • • • • • • • •',
    ' • • • • • • • •',
    ' • • - • • • • - • • • • • • • - • •',
    ' • • • • • • • • •',
    ' • • • • • • • • • •',
    ' • • • • • • • • • •',
    ' • • • • • • • • • • •',
    'n/a',
    '87 • • • • • • • • • •',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA 2 Fields Title 2',
    'Location',
    'BSB Code',
    'Sort Code',
    'Bank Code',
    'Transit Number',
    'ACH routing number',
    'Bank Code',
    'Bank Code',
    'n/a',
    'Bank Code',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'GA 2 Fields Value 2',
    'Germany (Europe)',
    '01 • • • •',
    '0 • • • • •',
    '04',
    '10 • • •',
    '02 • • • • • • •',
    7153,
    '0005',
    'n/a',
    '003',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
];

const paymentMethodData = [
  ['', 'AU', 'NZ', 'UK', 'EU', 'US', 'JP', 'CA', 'SG', 'HK', 'CN', 'MY'],
  [
    'Checkout Payment Method 1',
    'Apple Pay',
    'Apple Pay',
    'Apple Pay',
    'Apple Pay',
    'Apple Pay',
    'Apple Pay',
    'Apple Pay',
    'Apple Pay',
    'Alipay',
    'Alipay',
    'N/A',
  ],
  [
    'Checkout Payment Method 2',
    'Google Pay',
    'Google Pay',
    'Google Pay',
    'Google Pay',
    'Google Pay',
    'Google Pay',
    'Google Pay',
    'Google Pay',
    'WeChat Pay',
    'WeChat Pay',
    'N/A',
  ],
  [
    'Checkout Payment Method 3',
    'PayPal',
    'PayPal',
    'PayPal',
    'PayPal',
    'PayPal',
    'PayPal',
    'PayPal',
    'PayPal',
    '',
    '',
    'N/A',
  ],
  [
    'LMP Payment Method 1',
    'Alipay',
    'Alipay',
    'Klarna',
    'Klarna',
    'Alipay',
    'Konbini',
    'Alipay',
    'GrabPay',
    'Alipay',
    'Alipay',
    '',
  ],
  [
    'LMP Payment Method 2',
    'WeChat Pay',
    'WeChat Pay',
    'Trustly',
    'Trustly',
    'WeChat Pay',
    'Payeasy',
    'WeChat Pay',
    'PayNow',
    'WeChat Pay',
    'WeChat Pay',
    '',
  ],
  [
    'LMP Payment Method 3',
    'KakaoPay',
    'KakaoPay',
    'Paysafecard',
    'Paysafecard',
    'KakaoPay',
    'GrabPay',
    'KakaoPay',
    'WeChat Pay',
    'Apple Pay',
    'Apple Pay',
    '',
  ],
  [
    'LMP Payment Method 4',
    'GrabPay',
    'GrabPay',
    'iDEAL',
    'iDEAL',
    'GrabPay',
    'WeChat Pay',
    'GrabPay',
    'Alipay',
    'Google Pay',
    'Google Pay',
    '',
  ],
  [
    'LMP Payment Method 5',
    'Konbini',
    'Konbini',
    'Alipay',
    'Alipay',
    'Konbini',
    'Alipay',
    'Konbini',
    'KakaoPay',
    'PayPal',
    'PayPal',
    '',
  ],
  [
    'LMP Payment Method 6',
    'Klarna',
    'Klarna',
    'KakaoPay',
    'KakaoPay',
    'Klarna',
    'KakaoPay',
    'Klarna',
    'Konbini',
    'GrabPay',
    'GrabPay',
    '',
  ],
  [
    'LMP Payment Method 7',
    'iDEAL',
    'iDEAL',
    'GrabPay',
    'GrabPay',
    'iDEAL',
    'Klarna',
    'iDEAL',
    'Klarna',
    'KakaoPay',
    'KakaoPay',
    '',
  ],
];

const transfers = [
  [
    'Account location/corpsite region',
    'Europe (SEPA)',
    'Australia',
    'United Kingdom',
    'New Zealand',
    'Canada',
    'United States',
    'Singapore',
    'Japan',
    'Indonesia',
    'Hong Kong SAR',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Collection Currencies',
    'EUR',
    'AUD',
    'GBP',
    'NZD',
    'CAD',
    'USD',
    'SGD',
    'JPY',
    'IDR',
    'HKD',
    'CNY',
    'EUR',
    'USD',
    'AUD',
    'CAD',
    'CHF',
    'GBP',
    'JPY',
    'NZD',
    'SGD',
  ],
  [
    ' GA Page GA cards module (4 fields)',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Title 1',
    'IBAN',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
  ],
  [
    'Value 1',
    '90********',
    'Australia',
    'United Kingdom',
    'New Zealand',
    'Canada',
    '84********',
    '15********',
    '',
    '87*********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
    '87**********',
  ],
  [
    'Title 2',
    'Account Location',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'ACH routing number',
    'Bank Code',
    'Bank Code',
    'Account Type',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
    'Bank Code',
  ],
  [
    'Value 2',
    'Germany (Europe)',
    '61*******',
    '03******',
    '04-****-*******-**',
    '29*******',
    '02*******',
    7153,
    '',
    'Checking',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
    '003',
  ],
  [
    'Title 3',
    'Bank name',
    'BSB Code',
    'Sort Code',
    'Bank Code',
    'Transit Number',
    'Account Type',
    'Branch Code',
    'Branch Code',
    'Account Location',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
    'Branch Code',
  ],
  [
    'Value 3',
    'Banking Circle S.A.',
    13943,
    '0*****',
    '04',
    10009,
    'Checking',
    '001',
    '',
    'Indonesia',
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
    875,
  ],
  [
    'Title 4',
    '',
    '',
    '',
    'Branch Code',
    'Financial Institution Number',
    'SWIFT Code',
    'SWIFT Code',
    'Account Type',
    '',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
    'SWIFT Code',
  ],
  [
    'Value 4',
    '',
    '',
    '',
    2024,
    352,
    'C*******',
    'CHA******',
    'Checking',
    '',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
    'SCB*****',
  ],
  [
    'GA Page Why Section (4 fields)',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Title 1',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'Account Name',
    'n/a',
    'Account Name',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Value 1',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'Makers Supply Limited',
    'n/a',
    'Makers Supply Limited',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Title 2',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'Account Location',
    'n/a',
    'Account Location',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Value 2',
    'Germany (Europe)',
    'Australia',
    'United Kingdom',
    'New Zealand',
    'Canada',
    'United States',
    'Singapore',
    'Japan',
    'n/a',
    'Hong Kong SAR',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Title 3',
    'IBAN',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'n/a',
    'Account no. ',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Value 3',
    '90********',
    '61*******',
    '03******',
    '04-****-*******-**',
    '29*******',
    '84********',
    '15********',
    '',
    'n/a',
    '87**********',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Title 4',
    'Capabilities',
    'BSB Code',
    'Sort Code',
    'Bank Code',
    'Transit Number',
    'ACH routing number',
    'Bank Code',
    'Bank Code',
    'n/a',
    'Bank Code',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Value 4',
    'Domestic SEPA Transfer',
    '01****',
    '0*****',
    '04',
    '10***',
    '02*******',
    7153,
    '',
    'n/a',
    '003',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Images with 2 fields',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Title 1',
    'IBAN',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'Account no. ',
    'n/a',
    'Account no. ',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Value 1',
    '90********',
    '61*******',
    '03******',
    '04-****-*******-**',
    '29*******',
    '84********',
    '15********',
    '',
    'n/a',
    '87**********',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Title 2',
    'Location',
    'BSB Code',
    'Sort Code',
    'Bank Code',
    'Transit Number',
    'ACH routing number',
    'Bank Code',
    'Bank Code',
    'n/a',
    'Bank Code',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Value 2',
    'Germany (Europe)',
    '01****',
    '0*****',
    '04',
    '10***',
    '02*******',
    7153,
    '',
    'n/a',
    '003',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
];

const temp = {};

for (let i = 2; i < gaData.length; i++) {
  const row = gaData[i];
  for (let j = 1; j < row.length; j++) {
    if (gaData[0][j] != '') {
      temp[gaData[0][j]] = {
        ...temp[gaData[0][j]],
        ['awx-' + row[0].toLowerCase().replaceAll(' ', '-')]: gaData[i][j],
      };
    }
  }
}

for (let i = 1; i < paymentMethodData.length; i++) {
  const row = paymentMethodData[i];
  for (let j = 1; j < row.length; j++) {
    temp[paymentMethodData[0][j]] = {
      ...temp[paymentMethodData[0][j]],
      ['awx-' + row[0].toLowerCase().replaceAll(' ', '-')]: paymentMethodData[i][j],
    };
  }
}

console.log(temp);

for (let i = 1; i < transferData.length; i++) {
  const row = transferData[i];
  for (let j = 1; j < row.length; j++) {
    temp[transferData[0][j]] = {
      ...temp[transferData[0][j]],
      ['awx-' + row[0].toLowerCase().replaceAll(' ', '-')]: transferData[i][j],
    };
  }
}

// console.log(temp)

const res = {};

Object.keys(temp).forEach((key) => {
  const region = key.split('-')[0];
  res[region] = [...(res[region] || []), temp[key]];
});

console.log(res);

Object.keys(sheetData).forEach((key) => {
  temp[key] = {
    ...sheetData[key],
    ...newData[key],
  };
});
