export const sheetData = {
  EU: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'Europe',
    'awx-ga-cards-title-2': 'IBAN',
    'awx-ga-cards-value-2': '• • • • • • • • • •',
    'awx-ga-cards-title-3': 'SWIFT Code',
    'awx-ga-cards-value-3': '• • • • • • • •',
    'awx-ga-cards-title-4': 'Account Name',
    'awx-ga-cards-value-4': 'EUR Global Account',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Europe',
    'awx-ga-why-title-3': 'IBAN',
    'awx-ga-why-value-3': '• • • • • • • • • •',
    'awx-ga-why-title-4': 'SWIFT Code',
    'awx-ga-why-value-4': '• • • • • • • •',
    'awx-ga-2-fields-title-1': 'IBAN',
    'awx-ga-2-fields-value-1': '• • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Location',
    'awx-ga-2-fields-value-2': 'Europe',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Klarna',
    'awx-lmp-payment-method-1-icon': 'klarna',
    'awx-lmp-payment-method-2': 'Trustly',
    'awx-lmp-payment-method-2-icon': 'trustly',
    'awx-lmp-payment-method-3': 'Paysafecard',
    'awx-lmp-payment-method-3-icon': 'paysafecard',
    'awx-lmp-payment-method-4': 'iDEAL',
    'awx-lmp-payment-method-4-icon': 'ideal',
    'awx-lmp-payment-method-5': 'SEPA Direct Debit',
    'awx-lmp-payment-method-5-icon': 'SEPA',
    'awx-lmp-payment-method-6': 'KakaoPay',
    'awx-lmp-payment-method-6-icon': 'kakaopay',
    'awx-lmp-payment-method-7': 'GrabPay',
    'awx-lmp-payment-method-7-icon': 'grabpay',
  },
  AU: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'Australia',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • • •',
    'awx-ga-cards-title-3': 'BSB Code',
    'awx-ga-cards-value-3': '• • • • • •',
    'awx-ga-cards-title-4': 'Account Type',
    'awx-ga-cards-value-4': 'Current',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Australia',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • •',
    'awx-ga-why-title-4': 'BSB Code',
    'awx-ga-why-value-4': '• • • • • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • •',
    'awx-ga-2-fields-title-2': 'BSB Code',
    'awx-ga-2-fields-value-2': '• • • • • •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  UK: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'United Kingdom',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • •',
    'awx-ga-cards-title-3': 'IBAN',
    'awx-ga-cards-value-3': '• • • • • • • • • •',
    'awx-ga-cards-title-4': 'Sort Code',
    'awx-ga-cards-value-4': '• • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'United Kingdom',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • •',
    'awx-ga-why-title-4': 'Sort Code',
    'awx-ga-why-value-4': '• • • • • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • •',
    'awx-ga-2-fields-title-2': 'Sort Code',
    'awx-ga-2-fields-value-2': '• • • • • •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Klarna',
    'awx-lmp-payment-method-1-icon': 'klarna',
    'awx-lmp-payment-method-2': 'Trustly',
    'awx-lmp-payment-method-2-icon': 'trustly',
    'awx-lmp-payment-method-3': 'Paysafecard',
    'awx-lmp-payment-method-3-icon': 'paysafecard',
    'awx-lmp-payment-method-4': 'iDEAL',
    'awx-lmp-payment-method-4-icon': 'ideal',
    'awx-lmp-payment-method-5': 'Bacs Direct Debit',
    'awx-lmp-payment-method-5-icon': 'BACS',
    'awx-lmp-payment-method-6': 'KakaoPay',
    'awx-lmp-payment-method-6-icon': 'kakaopay',
    'awx-lmp-payment-method-7': 'GrabPay',
    'awx-lmp-payment-method-7-icon': 'grabpay',
  },
  NZ: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'New Zealand',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • - • •',
    'awx-ga-cards-title-3': 'Bank Code',
    'awx-ga-cards-value-3': '• •',
    'awx-ga-cards-title-4': 'Branch Code',
    'awx-ga-cards-value-4': '• • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'New Zealand',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • - • • • • - • • • • • • • - • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '• •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • - • • • • - • • • • • • • - • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '• •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  CA: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'Canada',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • • •',
    'awx-ga-cards-title-3': 'Transit Number',
    'awx-ga-cards-value-3': '• • • • •',
    'awx-ga-cards-title-4': 'Financial Institution Number',
    'awx-ga-cards-value-4': '• • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Canada',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • •',
    'awx-ga-why-title-4': 'Transit Number',
    'awx-ga-why-value-4': '• • • • • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Transit Number',
    'awx-ga-2-fields-value-2': '• • • • • •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  US: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • •',
    'awx-ga-cards-title-2': 'ACH routing no.',
    'awx-ga-cards-value-2': '• • • • • • • • •',
    'awx-ga-cards-title-3': 'Fedwire routing no.',
    'awx-ga-cards-value-3': '• • • • • • • • •',
    'awx-ga-cards-title-4': 'SWIFT Code',
    'awx-ga-cards-value-4': '• • • • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'United States',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • •',
    'awx-ga-why-title-4': 'Routing number',
    'awx-ga-why-value-4': '• • • • • • • • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Routing no.',
    'awx-ga-2-fields-value-2': '• • • • • • • • •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'ACH Direct Debit',
    'awx-lmp-payment-method-1-icon': 'ACH',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  SG: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • •',
    'awx-ga-cards-title-2': 'Bank Code',
    'awx-ga-cards-value-2': '• • • •',
    'awx-ga-cards-title-3': 'Branch Code',
    'awx-ga-cards-value-3': '• • •',
    'awx-ga-cards-title-4': 'SWIFT Code',
    'awx-ga-cards-value-4': '• • • • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Singapore',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '• • • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '• • • •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'GrabPay',
    'awx-lmp-payment-method-1-icon': 'grabpay',
    'awx-lmp-payment-method-2': 'PayNow',
    'awx-lmp-payment-method-2-icon': 'paynow',
    'awx-lmp-payment-method-3': 'WeChat Pay',
    'awx-lmp-payment-method-3-icon': 'wechat',
    'awx-lmp-payment-method-4': 'Alipay',
    'awx-lmp-payment-method-4-icon': 'alipay',
    'awx-lmp-payment-method-5': 'KakaoPay',
    'awx-lmp-payment-method-5-icon': 'kakaopay',
    'awx-lmp-payment-method-6': 'Konbini',
    'awx-lmp-payment-method-6-icon': 'konbini',
    'awx-lmp-payment-method-7': 'Klarna',
    'awx-lmp-payment-method-7-icon': 'klarna',
  },
  JP: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • •',
    'awx-ga-cards-title-2': 'Bank Code',
    'awx-ga-cards-value-2': '• • • •',
    'awx-ga-cards-title-3': 'Branch Code',
    'awx-ga-cards-value-3': '• • •',
    'awx-ga-cards-title-4': 'Account Type',
    'awx-ga-cards-value-4': 'Ordinary',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Japan',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '• • • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '• • • •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Konbini',
    'awx-lmp-payment-method-1-icon': 'konbini',
    'awx-lmp-payment-method-2': 'Payeasy',
    'awx-lmp-payment-method-2-icon': 'payeasy',
    'awx-lmp-payment-method-3': 'GrabPay',
    'awx-lmp-payment-method-3-icon': 'grabpay',
    'awx-lmp-payment-method-4': 'WeChat Pay',
    'awx-lmp-payment-method-4-icon': 'wechat',
    'awx-lmp-payment-method-5': 'Alipay',
    'awx-lmp-payment-method-5-icon': 'alipay',
    'awx-lmp-payment-method-6': 'KakaoPay',
    'awx-lmp-payment-method-6-icon': 'kakaopay',
    'awx-lmp-payment-method-7': 'Klarna',
    'awx-lmp-payment-method-7-icon': 'klarna',
  },
  ID: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • • • •',
    'awx-ga-cards-title-2': 'Account Type',
    'awx-ga-cards-value-2': 'Checking',
    'awx-ga-cards-title-3': 'Location',
    'awx-ga-cards-value-3': 'Indonesia',
    'awx-ga-cards-title-4': 'Account Type',
    'awx-ga-cards-value-4': 'Checking',
    'awx-ga-why-title-1': 'n/a',
    'awx-ga-why-value-1': 'n/a',
    'awx-ga-why-title-2': 'n/a',
    'awx-ga-why-value-2': 'n/a',
    'awx-ga-why-title-3': 'n/a',
    'awx-ga-why-value-3': 'n/a',
    'awx-ga-why-title-4': 'n/a',
    'awx-ga-why-value-4': 'n/a',
    'awx-ga-2-fields-title-1': 'n/a',
    'awx-ga-2-fields-value-1': 'n/a',
    'awx-ga-2-fields-title-2': 'n/a',
    'awx-ga-2-fields-value-2': 'n/a',
  },
  HK: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • • •',
    'awx-ga-cards-title-2': 'Bank Code',
    'awx-ga-cards-value-2': '• • •',
    'awx-ga-cards-title-3': 'Branch Code',
    'awx-ga-cards-value-3': '• • •',
    'awx-ga-cards-title-4': 'SWIFT Code',
    'awx-ga-cards-value-4': '• • • • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Hong Kong SAR',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • • • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '• • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '• • •',
    'awx-checkout-payment-method-1': 'Alipay HK',
    'awx-checkout-payment-method-1-icon': 'alipayhk',
    'awx-checkout-payment-method-2': 'WeChat Pay',
    'awx-checkout-payment-method-2-icon': 'wechat',
    'awx-checkout-payment-method-3': 'FPS',
    'awx-checkout-payment-method-3-icon': 'FPS',
    'awx-lmp-payment-method-1': 'Alipay HK',
    'awx-lmp-payment-method-1-icon': 'alipayhk',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'FPS',
    'awx-lmp-payment-method-3-icon': 'FPS',
    'awx-lmp-payment-method-4': 'Apple Pay',
    'awx-lmp-payment-method-4-icon': 'apple pay',
    'awx-lmp-payment-method-5': 'Google Pay',
    'awx-lmp-payment-method-5-icon': 'google pay',
    'awx-lmp-payment-method-6': 'PayPal',
    'awx-lmp-payment-method-6-icon': 'paypal',
    'awx-lmp-payment-method-7': 'GrabPay',
    'awx-lmp-payment-method-7-icon': 'grabpay',
  },
  CN: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • • •',
    'awx-ga-cards-title-2': 'Bank Code',
    'awx-ga-cards-value-2': '• • •',
    'awx-ga-cards-title-3': 'Branch Code',
    'awx-ga-cards-value-3': '• • •',
    'awx-ga-cards-title-4': 'SWIFT Code',
    'awx-ga-cards-value-4': '• • • • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Hong Kong SAR',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • • • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '• • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '• • •',
    'awx-checkout-payment-method-1': 'Alipay',
    'awx-checkout-payment-method-1-icon': 'alipay',
    'awx-checkout-payment-method-2': 'WeChat Pay',
    'awx-checkout-payment-method-2-icon': 'wechat',
    'awx-checkout-payment-method-3': 'Kakao Pay',
    'awx-checkout-payment-method-3-icon': 'kakao',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'Kakao Pay',
    'awx-lmp-payment-method-3-icon': 'kakao',
    'awx-lmp-payment-method-4': 'Klarna',
    'awx-lmp-payment-method-4-icon': 'Klarna',
    'awx-lmp-payment-method-5': 'PayPal',
    'awx-lmp-payment-method-5-icon': 'paypal',
    'awx-lmp-payment-method-6': 'Google Pay',
    'awx-lmp-payment-method-6-icon': 'google pay',
    'awx-lmp-payment-method-7': 'Apple Pay',
    'awx-lmp-payment-method-7-icon': 'apple pay',
  },
  MY: {
    'awx-checkout-payment-method-1': 'N/A',
    'awx-checkout-payment-method-1-icon': 'n/a',
    'awx-checkout-payment-method-2': 'N/A',
    'awx-checkout-payment-method-2-icon': 'n/a',
    'awx-checkout-payment-method-3': 'N/A',
    'awx-checkout-payment-method-3-icon': 'n/a',
    'awx-lmp-payment-method-1': '  ',
    'awx-lmp-payment-method-1-icon': '  ',
    'awx-lmp-payment-method-2': '  ',
    'awx-lmp-payment-method-2-icon': '  ',
    'awx-lmp-payment-method-3': '  ',
    'awx-lmp-payment-method-3-icon': '  ',
    'awx-lmp-payment-method-4': '  ',
    'awx-lmp-payment-method-4-icon': '  ',
    'awx-lmp-payment-method-5': '  ',
    'awx-lmp-payment-method-5-icon': '  ',
    'awx-lmp-payment-method-6': '  ',
    'awx-lmp-payment-method-6-icon': '  ',
    'awx-lmp-payment-method-7': '  ',
    'awx-lmp-payment-method-7-icon': '  ',
  },
};

const transferData = {
  US: [
    {
      'awx-transfer-method': 'ACH',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'Bank of America',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 325099196074,
      'awx-bank-detail-title-4': 'ABA Code',
      'awx-bank-detail-value-4': 21000322,
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2':
        '635 Red Bud Lane, Teterboro, New Jersey 07608, United States of America',
    },
    {
      'awx-transfer-method': 'Fedwire',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'Bank of America',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 325099196074,
      'awx-bank-detail-title-4': 'ABA Code',
      'awx-bank-detail-value-4': 21000322,
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2':
        '635 Red Bud Lane, Teterboro, New Jersey 07608, United States of America',
    },
    {
      'awx-transfer-method': 'SWIFT',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'AIB BANK',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account NUmber',
      'awx-bank-detail-value-3': 325099196074,
      'awx-bank-detail-title-4': 'SWIFT Code',
      'awx-bank-detail-value-4': 'AIBKUS3TTMK',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2':
        '635 Red Bud Lane, Teterboro, New Jersey 07608, United States of America',
    },
  ],
  NZ: [
    {
      'awx-transfer-method': 'Local',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'ANZ Bank New Zealand',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 100017777777333,
      'awx-bank-detail-title-4': '  ',
      'awx-bank-detail-value-4': '  ',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': '48 Shortland St., Auckland, New Zealand 1010',
    },
    {
      'awx-transfer-method': 'SWIFT',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'SWIFT Code',
      'awx-bank-detail-value-4': 'HSBCXX2S202',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
  ],
  UK: [
    {
      'awx-transfer-method': 'EUR Local',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'IBAN Code',
      'awx-bank-detail-value-4': 'GB5920708009006378',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
    {
      'awx-transfer-method': 'GBP Local',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC Britain Branch',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'Sort Code ',
      'awx-bank-detail-value-4': '12-34-56',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
    {
      'awx-transfer-method': 'SWIFT',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'IBAN Code',
      'awx-bank-detail-value-4': 'XX5920708009006378',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
  ],
  SG: [
    {
      'awx-transfer-method': 'GIRO',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'Bank Code',
      'awx-bank-detail-value-4': 7171082,
      'awx-bank-detail-title-5': 'SWIFT Code',
      'awx-bank-detail-value-5': 'HSBCSG2S202',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
    {
      'awx-transfer-method': 'RTGS',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'Bank Code',
      'awx-bank-detail-value-4': 7171082,
      'awx-bank-detail-title-5': 'SWIFT Code',
      'awx-bank-detail-value-5': 'HSBCSG2S202',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
    {
      'awx-transfer-method': 'FAST',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'Bank Code',
      'awx-bank-detail-value-4': 7171082,
      'awx-bank-detail-title-5': 'SWIFT Code',
      'awx-bank-detail-value-5': 'HSBCSG2S202',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
    {
      'awx-transfer-method': 'SWIFT',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'SWIFT Code',
      'awx-bank-detail-value-4': 'HSBCXX2S202',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
  ],
  EU: [
    {
      'awx-transfer-method': 'Local',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'SWIFT Code',
      'awx-bank-detail-value-4': 'HSBCXX2S202',
      'awx-bank-detail-title-5': 'IBAN Code',
      'awx-bank-detail-value-5': 'XX5920708009006378',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
    {
      'awx-transfer-method': 'SWIFT',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'SWIFT Code',
      'awx-bank-detail-value-4': 'HSBCXX2S202',
      'awx-bank-detail-title-5': 'IBAN Code',
      'awx-bank-detail-value-5': 'XX5920708009006378',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
  ],
  JP: [
    {
      'awx-transfer-method': 'Local',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC Japan Branch',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'Zengin Code',
      'awx-bank-detail-value-4': 1234567,
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
    {
      'awx-transfer-method': 'SWIFT',
      'awx-bank-detail-title-1': 'Bank Name',
      'awx-bank-detail-value-1': 'HSBC',
      'awx-bank-detail-title-2': 'Account Name',
      'awx-bank-detail-value-2': 'Thomas Leaver',
      'awx-bank-detail-title-3': 'Account Number',
      'awx-bank-detail-value-3': 123456,
      'awx-bank-detail-title-4': 'SWIFT Code',
      'awx-bank-detail-value-4': 'HSBCXX2S202',
      'awx-bank-detail-title-5': '  ',
      'awx-bank-detail-value-5': '  ',
      'awx-recipient-detail-title-1': 'Name',
      'awx-recipient-detail-value-1': 'Thomas Leaver',
      'awx-recipient-detail-title-2': 'Address',
      'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
    },
  ],
};

export const transferMethodData = {
  AU: {
    'awx-transfer-method-1': 'Bank Transfer',
    'awx-speed-1': '0-1 business day',
    'awx-transfer-method-2': 'SWIFT',
    'awx-speed-2': '0-3 business days ',
    'awx-transfer-method-3': '  ',
    'awx-speed-3': '  ',
  },
  NZ: {
    'awx-transfer-method-1': 'Direct Credit',
    'awx-speed-1': '0-1 business day',
    'awx-transfer-method-2': 'SWIFT',
    'awx-speed-2': '0-3 business days ',
    'awx-transfer-method-3': '  ',
    'awx-speed-3': '  ',
  },
  UK: {
    'awx-transfer-method-1': 'Faster Payments',
    'awx-speed-1': '0-1 business day',
    'awx-transfer-method-2': 'BACS',
    'awx-speed-2': '1-2 business days',
    'awx-transfer-method-3': 'CHAPS',
    'awx-speed-3': '0-1 business day',
  },
  EU: {
    'awx-transfer-method-1': 'SEPA',
    'awx-speed-1': '0-1 business day',
    'awx-transfer-method-2': 'SWIFT',
    'awx-speed-2': '0-3 business days ',
    'awx-transfer-method-3': '  ',
    'awx-speed-3': '  ',
  },
  US: {
    'awx-transfer-method-1': 'ACH',
    'awx-speed-1': '1-2 business days',
    'awx-transfer-method-2': 'Fedwire',
    'awx-speed-2': '0-1 business day',
    'awx-transfer-method-3': 'SWIFT',
    'awx-speed-3': '0-3 business days ',
  },
  JP: {
    'awx-transfer-method-1': 'Zengin',
    'awx-speed-1': '0-1 business day',
    'awx-transfer-method-2': 'SWIFT',
    'awx-speed-2': '0-3 business days ',
    'awx-transfer-method-3': '  ',
    'awx-speed-3': '  ',
  },
  CA: {
    'awx-transfer-method-1': 'EFT',
    'awx-speed-1': '0-1 business day',
    'awx-transfer-method-2': 'SWIFT',
    'awx-speed-2': '0-3 business days ',
    'awx-transfer-method-3': '  ',
    'awx-speed-3': '  ',
  },
  SG: {
    'awx-transfer-method-1': 'GIRO',
    'awx-speed-1': '0-1 business day',
    'awx-transfer-method-2': 'MEPS',
    'awx-speed-2': '0-1 business day',
    'awx-transfer-method-3': 'FAST',
    'awx-speed-3': '0-1 business day',
  },
  HK: {
    'awx-transfer-method-1': 'ACH',
    'awx-speed-1': '1-2 business days',
    'awx-transfer-method-2': 'RTGS',
    'awx-speed-2': '0-1 business day',
    'awx-transfer-method-3': 'FPS',
    'awx-speed-3': '0-1 business day',
  },
  CN: {
    'awx-transfer-method-1': 'ACH',
    'awx-speed-1': '1-2 business days',
    'awx-transfer-method-2': 'RTGS',
    'awx-speed-2': '0-1 business day',
    'awx-transfer-method-3': 'FPS',
    'awx-speed-3': '0-1 business day',
  },
  ID: {},
};

export const bankCardData = {
  US_ACH: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'Bank of America',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 325099196074,
    'awx-bank-detail-title-4': 'ABA Code',
    'awx-bank-detail-value-4': 21000322,
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2':
      '635 Red Bud Lane, Teterboro, New Jersey 07608, United States of America',
  },
  US_Fedwire: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'Bank of America',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 325099196074,
    'awx-bank-detail-title-4': 'ABA Code',
    'awx-bank-detail-value-4': 21000322,
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2':
      '635 Red Bud Lane, Teterboro, New Jersey 07608, United States of America',
  },
  US_SWIFT: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'AIB BANK',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 325099196074,
    'awx-bank-detail-title-4': 'SWIFT Code',
    'awx-bank-detail-value-4': 'AIBKUS3TTMK',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2':
      '635 Red Bud Lane, Teterboro, New Jersey 07608, United States of America',
  },
  NZ_Local: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'ANZ Bank New Zealand',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 100017777777333,
    'awx-bank-detail-title-4': '',
    'awx-bank-detail-value-4': '',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': '48 Shortland St., Auckland, New Zealand 1010',
  },
  NZ_SWIFT: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'SWIFT Code',
    'awx-bank-detail-value-4': 'HSBCXX2S202',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  UK_EUR_Local: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'IBAN Code',
    'awx-bank-detail-value-4': 'GB5920708009006378',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  UK_GBP_Local: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC Britain Branch',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'Sort Code',
    'awx-bank-detail-value-4': '12-34-56',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  UK_SWIFT: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'IBAN Code',
    'awx-bank-detail-value-4': 'XX5920708009006378',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  SG_GIRO: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'Bank Code',
    'awx-bank-detail-value-4': 7171082,
    'awx-bank-detail-title-5': 'SWIFT Code',
    'awx-bank-detail-value-5': 'HSBCSG2S202',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  SG_RTGS: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'Bank Code',
    'awx-bank-detail-value-4': 7171082,
    'awx-bank-detail-title-5': 'SWIFT Code',
    'awx-bank-detail-value-5': 'HSBCSG2S202',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  SG_FAST: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'Bank Code',
    'awx-bank-detail-value-4': 7171082,
    'awx-bank-detail-title-5': 'SWIFT Code',
    'awx-bank-detail-value-5': 'HSBCSG2S202',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  SG_SWIFT: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'SWIFT Code',
    'awx-bank-detail-value-4': 'HSBCXX2S202',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  Germany_Local: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'SWIFT Code',
    'awx-bank-detail-value-4': 'HSBCXX2S202',
    'awx-bank-detail-title-5': 'IBAN Code',
    'awx-bank-detail-value-5': 'XX5920708009006378',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  Germany_SWIFT: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'SWIFT Code',
    'awx-bank-detail-value-4': 'HSBCXX2S202',
    'awx-bank-detail-title-5': 'IBAN Code',
    'awx-bank-detail-value-5': 'XX5920708009006378',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  Brazil_Local: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'Banco do Brasil',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 1234567890,
    'awx-bank-detail-title-4': 'Bank Code',
    'awx-bank-detail-value-4': 1234,
    'awx-bank-detail-title-5': 'Branch Code',
    'awx-bank-detail-value-5': 1,
    'awx-bank-detail-title-6': 'Account Type',
    'awx-bank-detail-value-6': 'Savings',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  Brazil_SWIFT: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'SWIFT Code',
    'awx-bank-detail-value-4': 'HSBCXX2S202',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
  SA_SWIFT: {
    'awx-bank-detail-title-1': 'Bank Name',
    'awx-bank-detail-value-1': 'HSBC',
    'awx-bank-detail-title-2': 'Account Name',
    'awx-bank-detail-value-2': 'Thomas Leaver',
    'awx-bank-detail-title-3': 'Account Number',
    'awx-bank-detail-value-3': 123456,
    'awx-bank-detail-title-4': 'SWIFT Code',
    'awx-bank-detail-value-4': 'HSBCXX2S202',
    'awx-bank-detail-title-5': '',
    'awx-bank-detail-value-5': '',
    'awx-bank-detail-title-6': '',
    'awx-bank-detail-value-6': '',
    'awx-recipient-detail-title-1': 'Name',
    'awx-recipient-detail-value-1': 'Thomas Leaver',
    'awx-recipient-detail-title-2': 'Address',
    'awx-recipient-detail-value-2': 'Level 7/20 William St., Melbourne, VIC 1234, Australia',
  },
};
