export const sheetData = {
  EU: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'Europe',
    'awx-ga-cards-title-2': 'IBAN',
    'awx-ga-cards-value-2': '• • • • • • • • • •',
    'awx-ga-cards-title-3': 'SWIFT Code',
    'awx-ga-cards-value-3': '• • • • • • • •',
    'awx-ga-cards-title-4': 'Account Name',
    'awx-ga-cards-value-4': 'EUR Global Account',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Europe',
    'awx-ga-why-title-3': 'IBAN',
    'awx-ga-why-value-3': '• • • • • • • • • •',
    'awx-ga-why-title-4': 'SWIFT Code',
    'awx-ga-why-value-4': 'LHVBEE22',
    'awx-ga-2-fields-title-1': 'IBAN',
    'awx-ga-2-fields-value-1': '• • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Location',
    'awx-ga-2-fields-value-2': 'Europe',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Klarna',
    'awx-lmp-payment-method-1-icon': 'klarna',
    'awx-lmp-payment-method-2': 'Trustly',
    'awx-lmp-payment-method-2-icon': 'trustly',
    'awx-lmp-payment-method-3': 'Paysafecard',
    'awx-lmp-payment-method-3-icon': 'paysafecard',
    'awx-lmp-payment-method-4': 'iDEAL',
    'awx-lmp-payment-method-4-icon': 'ideal',
    'awx-lmp-payment-method-5': 'Alipay',
    'awx-lmp-payment-method-5-icon': 'alipay',
    'awx-lmp-payment-method-6': 'KakaoPay',
    'awx-lmp-payment-method-6-icon': 'kakaopay',
    'awx-lmp-payment-method-7': 'GrabPay',
    'awx-lmp-payment-method-7-icon': 'grabpay',
  },
  AU: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'Australia',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • • •',
    'awx-ga-cards-title-3': 'BSB Code',
    'awx-ga-cards-value-3': '• • • • • •',
    'awx-ga-cards-title-4': 'Account Type',
    'awx-ga-cards-value-4': 'Current',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Australia',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • •',
    'awx-ga-why-title-4': 'BSB Code',
    'awx-ga-why-value-4': '013943',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • •',
    'awx-ga-2-fields-title-2': 'BSB Code',
    'awx-ga-2-fields-value-2': '013943',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  UK: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'United Kingdom',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • •',
    'awx-ga-cards-title-3': 'IBAN',
    'awx-ga-cards-value-3': '• • • • • • • • • •',
    'awx-ga-cards-title-4': 'Sort Code',
    'awx-ga-cards-value-4': '• • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'United Kingdom',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • •',
    'awx-ga-why-title-4': 'Sort Code',
    'awx-ga-why-value-4': '040072',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • •',
    'awx-ga-2-fields-title-2': 'Sort Code',
    'awx-ga-2-fields-value-2': '040072',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Klarna',
    'awx-lmp-payment-method-1-icon': 'klarna',
    'awx-lmp-payment-method-2': 'Trustly',
    'awx-lmp-payment-method-2-icon': 'trustly',
    'awx-lmp-payment-method-3': 'Paysafecard',
    'awx-lmp-payment-method-3-icon': 'paysafecard',
    'awx-lmp-payment-method-4': 'iDEAL',
    'awx-lmp-payment-method-4-icon': 'ideal',
    'awx-lmp-payment-method-5': 'Alipay',
    'awx-lmp-payment-method-5-icon': 'alipay',
    'awx-lmp-payment-method-6': 'KakaoPay',
    'awx-lmp-payment-method-6-icon': 'kakaopay',
    'awx-lmp-payment-method-7': 'GrabPay',
    'awx-lmp-payment-method-7-icon': 'grabpay',
  },
  NZ: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'New Zealand',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • - • •',
    'awx-ga-cards-title-3': 'Bank Code',
    'awx-ga-cards-value-3': '• •',
    'awx-ga-cards-title-4': 'Branch Code',
    'awx-ga-cards-value-4': '• • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'New Zealand',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • - • • • • - • • • • • • • - • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '04',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • - • • • • - • • • • • • • - • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '04',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  CA: {
    'awx-ga-cards-title-1': 'Location',
    'awx-ga-cards-value-1': 'Canada',
    'awx-ga-cards-title-2': 'Account no. ',
    'awx-ga-cards-value-2': '• • • • • • • • •',
    'awx-ga-cards-title-3': 'Transit Number',
    'awx-ga-cards-value-3': '• • • • •',
    'awx-ga-cards-title-4': 'Financial Institution Number',
    'awx-ga-cards-value-4': '• • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Canada',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • •',
    'awx-ga-why-title-4': 'Transit Number',
    'awx-ga-why-value-4': 10009,
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Transit Number',
    'awx-ga-2-fields-value-2': 10009,
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  US: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • •',
    'awx-ga-cards-title-2': 'ACH routing no.',
    'awx-ga-cards-value-2': '• • • • • • • • •',
    'awx-ga-cards-title-3': 'Fedwire routing no.',
    'awx-ga-cards-value-3': '• • • • • • • • •',
    'awx-ga-cards-title-4': 'SWIFT Code',
    'awx-ga-cards-value-4': '• • • • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'United States',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • •',
    'awx-ga-why-title-4': 'Routing number',
    'awx-ga-why-value-4': '• • • • • • • • •',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Routing no.',
    'awx-ga-2-fields-value-2': '• • • • • • • • •',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'KakaoPay',
    'awx-lmp-payment-method-3-icon': 'kakaopay',
    'awx-lmp-payment-method-4': 'GrabPay',
    'awx-lmp-payment-method-4-icon': 'grabpay',
    'awx-lmp-payment-method-5': 'Konbini',
    'awx-lmp-payment-method-5-icon': 'konbini',
    'awx-lmp-payment-method-6': 'Klarna',
    'awx-lmp-payment-method-6-icon': 'klarna',
    'awx-lmp-payment-method-7': 'iDEAL',
    'awx-lmp-payment-method-7-icon': 'ideal',
  },
  SG: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • •',
    'awx-ga-cards-title-2': 'Bank Code',
    'awx-ga-cards-value-2': 7153,
    'awx-ga-cards-title-3': 'Branch Code',
    'awx-ga-cards-value-3': '• • •',
    'awx-ga-cards-title-4': 'SWIFT Code',
    'awx-ga-cards-value-4': '• • • • • • • •',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Singapore',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': 7153,
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': 7153,
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'GrabPay',
    'awx-lmp-payment-method-1-icon': 'grabpay',
    'awx-lmp-payment-method-2': 'PayNow',
    'awx-lmp-payment-method-2-icon': 'paynow',
    'awx-lmp-payment-method-3': 'WeChat Pay',
    'awx-lmp-payment-method-3-icon': 'wechat',
    'awx-lmp-payment-method-4': 'Alipay',
    'awx-lmp-payment-method-4-icon': 'alipay',
    'awx-lmp-payment-method-5': 'KakaoPay',
    'awx-lmp-payment-method-5-icon': 'kakaopay',
    'awx-lmp-payment-method-6': 'Konbini',
    'awx-lmp-payment-method-6-icon': 'konbini',
    'awx-lmp-payment-method-7': 'Klarna',
    'awx-lmp-payment-method-7-icon': 'klarna',
  },
  JP: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • •',
    'awx-ga-cards-title-2': 'Bank Code',
    'awx-ga-cards-value-2': '0005',
    'awx-ga-cards-title-3': 'Branch Code',
    'awx-ga-cards-value-3': '• • •',
    'awx-ga-cards-title-4': 'Account Type',
    'awx-ga-cards-value-4': 'Ordinary',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Japan',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '0005',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '0005',
    'awx-checkout-payment-method-1': 'Apple Pay',
    'awx-checkout-payment-method-1-icon': 'apple pay',
    'awx-checkout-payment-method-2': 'Google Pay',
    'awx-checkout-payment-method-2-icon': 'google pay',
    'awx-checkout-payment-method-3': 'PayPal',
    'awx-checkout-payment-method-3-icon': 'paypal',
    'awx-lmp-payment-method-1': 'Konbini',
    'awx-lmp-payment-method-1-icon': 'konbini',
    'awx-lmp-payment-method-2': 'Payeasy',
    'awx-lmp-payment-method-2-icon': 'payeasy',
    'awx-lmp-payment-method-3': 'GrabPay',
    'awx-lmp-payment-method-3-icon': 'grabpay',
    'awx-lmp-payment-method-4': 'WeChat Pay',
    'awx-lmp-payment-method-4-icon': 'wechat',
    'awx-lmp-payment-method-5': 'Alipay',
    'awx-lmp-payment-method-5-icon': 'alipay',
    'awx-lmp-payment-method-6': 'KakaoPay',
    'awx-lmp-payment-method-6-icon': 'kakaopay',
    'awx-lmp-payment-method-7': 'Klarna',
    'awx-lmp-payment-method-7-icon': 'klarna',
  },
  ID: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • • • •',
    'awx-ga-cards-title-2': 'Account Type',
    'awx-ga-cards-value-2': 'Checking',
    'awx-ga-cards-title-3': 'Location',
    'awx-ga-cards-value-3': 'Indonesia',
    'awx-ga-cards-title-4': 'Account Type',
    'awx-ga-cards-value-4': 'Checking',
    'awx-ga-why-title-1': 'n/a',
    'awx-ga-why-value-1': 'n/a',
    'awx-ga-why-title-2': 'n/a',
    'awx-ga-why-value-2': 'n/a',
    'awx-ga-why-title-3': 'n/a',
    'awx-ga-why-value-3': 'n/a',
    'awx-ga-why-title-4': 'n/a',
    'awx-ga-why-value-4': 'n/a',
    'awx-ga-2-fields-title-1': 'n/a',
    'awx-ga-2-fields-value-1': 'n/a',
    'awx-ga-2-fields-title-2': 'n/a',
    'awx-ga-2-fields-value-2': 'n/a',
  },
  HK: {
    'awx-ga-cards-title-1': 'Account no. ',
    'awx-ga-cards-value-1': '• • • • • • • • • • •',
    'awx-ga-cards-title-2': 'Bank Code',
    'awx-ga-cards-value-2': '003',
    'awx-ga-cards-title-3': 'Branch Code',
    'awx-ga-cards-value-3': '• • •',
    'awx-ga-cards-title-4': 'SWIFT Code',
    'awx-ga-cards-value-4': 'SCBLHKHH',
    'awx-ga-why-title-1': 'Account Name',
    'awx-ga-why-value-1': 'Makers Supply Limited',
    'awx-ga-why-title-2': 'Location',
    'awx-ga-why-value-2': 'Hong Kong SAR',
    'awx-ga-why-title-3': 'Account no. ',
    'awx-ga-why-value-3': '• • • • • • • • • • • •',
    'awx-ga-why-title-4': 'Bank Code',
    'awx-ga-why-value-4': '003',
    'awx-ga-2-fields-title-1': 'Account no. ',
    'awx-ga-2-fields-value-1': '• • • • • • • • • • • •',
    'awx-ga-2-fields-title-2': 'Bank Code',
    'awx-ga-2-fields-value-2': '003',
    'awx-checkout-payment-method-1': 'Alipay',
    'awx-checkout-payment-method-1-icon': 'alipay',
    'awx-checkout-payment-method-2': 'WeChat Pay',
    'awx-checkout-payment-method-2-icon': 'wechat',
    'awx-checkout-payment-method-3': 'Apple pay',
    'awx-checkout-payment-method-3-icon': 'apple Pay',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'Apple Pay',
    'awx-lmp-payment-method-3-icon': 'apple pay',
    'awx-lmp-payment-method-4': 'Google Pay',
    'awx-lmp-payment-method-4-icon': 'google pay',
    'awx-lmp-payment-method-5': 'PayPal',
    'awx-lmp-payment-method-5-icon': 'paypal',
    'awx-lmp-payment-method-6': 'GrabPay',
    'awx-lmp-payment-method-6-icon': 'grabpay',
    'awx-lmp-payment-method-7': 'KakaoPay',
    'awx-lmp-payment-method-7-icon': 'kakaopay',
  },
  CN: {
    'awx-checkout-payment-method-1': 'Alipay',
    'awx-checkout-payment-method-1-icon': 'alipay',
    'awx-checkout-payment-method-2': 'WeChat Pay',
    'awx-checkout-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-1': 'Alipay',
    'awx-lmp-payment-method-1-icon': 'alipay',
    'awx-lmp-payment-method-2': 'WeChat Pay',
    'awx-lmp-payment-method-2-icon': 'wechat',
    'awx-lmp-payment-method-3': 'Apple Pay',
    'awx-lmp-payment-method-3-icon': 'apple pay',
    'awx-lmp-payment-method-4': 'Google Pay',
    'awx-lmp-payment-method-4-icon': 'google pay',
    'awx-lmp-payment-method-5': 'PayPal',
    'awx-lmp-payment-method-5-icon': 'paypal',
    'awx-lmp-payment-method-6': 'GrabPay',
    'awx-lmp-payment-method-6-icon': 'grabpay',
    'awx-lmp-payment-method-7': 'KakaoPay',
    'awx-lmp-payment-method-7-icon': 'kakaopay',
  },
  MY: {
    'awx-checkout-payment-method-1': 'N/A',
    'awx-checkout-payment-method-1-icon': 'n/a',
    'awx-checkout-payment-method-2': 'N/A',
    'awx-checkout-payment-method-2-icon': 'n/a',
    'awx-checkout-payment-method-3': 'N/A',
    'awx-checkout-payment-method-3-icon': 'n/a',
    'awx-lmp-payment-method-1': '  ',
    'awx-lmp-payment-method-1-icon': '  ',
    'awx-lmp-payment-method-2': '  ',
    'awx-lmp-payment-method-2-icon': '  ',
    'awx-lmp-payment-method-3': '  ',
    'awx-lmp-payment-method-3-icon': '  ',
    'awx-lmp-payment-method-4': '  ',
    'awx-lmp-payment-method-4-icon': '  ',
    'awx-lmp-payment-method-5': '  ',
    'awx-lmp-payment-method-5-icon': '  ',
    'awx-lmp-payment-method-6': '  ',
    'awx-lmp-payment-method-6-icon': '  ',
    'awx-lmp-payment-method-7': '  ',
    'awx-lmp-payment-method-7-icon': '  ',
  },
};
